### ISSUE TITLE
Gateway crashes

### ISSUE THREAD

**Issue by trivialkettle** [arobenko/mqtt-sn#19]
Hi,
i noticed another crash in the gateway.

Callstack:
```
<unknown> 0x00007ffff79b63f4
operator() GatewayApp.cpp:82
operator() GatewaySession.cpp:93
main main.cpp:49
```

I could reproduce this. I have a client that connects to the gateway and then later changes the last will. If I restart this programm the gateway crashes.

I removed the `assert` statement and then it crashes with this callstack:

```
std::__detail::_List_node_base::_M_unhook 0x00007ffff7cc323e
operator() GatewayApp.cpp:114
main main.cpp:49
```

I  will try to assemble a python script to show it.

Edit: I debuged some more, and found that `iter` is sometimes `NULL`.

**Comment by arobenko** [comment]
Done
