### ISSUE TITLE
Tests fail with Comms Champions 2.3.1

### ISSUE THREAD

**Issue by a1lu** [arobenko/mqtt-sn#6]
Hi,
To get rid of compiler warnings in cc (std::move local object into return)  I tried cc version 2.3.1. All client tests but the ones that use  `msg.field_duration()` fail (Test38, Test39). I debugged into `doSleep()` and saw that `field_duration` was set there. I don't understand where this field disappears  Would be nice if you could have a look at it.
Thanks.

Regards
ailu

**Comment by arobenko** [comment]
Should be fixed in [v0.9](https://github.com/arobenko/mqtt-sn/releases/tag/v0.9) release, please reopen if problem persists.
